MPLS: Editorial changes
detnet-wg/data-plane-drafts pull request #99
Opened 2020-05-29 15:10 UTC by vb-balazs

2020-05-29 15:24 UTC, dfedyk requested changes
Updated some English otherwise looks good. thanks Don

2020-05-29 15:24 UTC, dfedyk commented on mpls/draft-ietf-detnet-mpls.xml
> +       DetNet using MPLS forwarding processing is performed on the F-Label.  This
forwarding, processing

2020-05-29 15:24 UTC, dfedyk commented on mpls/draft-ietf-detnet-mpls.xml
> +	   During elimination and the replication process the
During the elimination and replication process,

2020-05-29 15:24 UTC, dfedyk commented on mpls/draft-ietf-detnet-mpls.xml
> +       maintain that state is such as way that it is available to the
maintain that state in such away

2020-05-29 15:24 UTC, dfedyk commented on mpls/draft-ietf-detnet-mpls.xml
> +	   the node may perform as unmodified LSRs that only understand
these nodes may perform

(Plural because the sentence begins with a plural. Alternatively talks about a singular node in the whole sentence.)

2020-05-29 15:24 UTC, dfedyk commented on mpls/draft-ietf-detnet-mpls.xml
> +       how to switch MPLS-TE LSPs, i.e., as a transit node,
transit nodes,

2020-05-30 05:23 UTC, vb-balazs commented
Thanks for Don's fine tuning.

2020-06-05 13:49 UTC, louberger approved these changes

2020-06-05 13:49 UTC, louberger commented on mpls/draft-ietf-detnet-mpls.xml
> +       copied to the corresponding egress DetNet member flow. Specifically, a relay node
isn't this supposed to be s/member/compound?

2020-06-05 13:49 UTC, louberger commented on mpls/draft-ietf-detnet-mpls.xml
> +       copied to the corresponding egress DetNet member flow. Specifically, a relay node
actually the next sentence makes it clear

2020-06-05 13:51 UTC, louberger commented
@dfedyk cam you review and merge if you're good with the changes.

2020-06-05 14:10 UTC, dfedyk approved these changes

2020-06-05 14:10 UTC, merged